export const TYPES = {
  ILearnerProfileModel: Symbol.for("ILearnerProfileModel"),
  IUserModel: Symbol.for("IUserModel"), //models
  IProfessionalProfileModel: Symbol.for("ProfesionalProfileModel"),
  IAdminProfileModel: Symbol.for("IAdminProfileModel"),
  ILearnerProfileRepo: Symbol.for("ILearnerProfileRepo"), //Repos
  IProfesionalProfileRepo: Symbol.for("IProfesionalProfileRepo"),
  IRedisRepository: Symbol.for("IRedisRepository"),
  IAdminProfile: Symbol.for("IAdminProfileRepository"),
  IUserRepo: Symbol.for("IUserRepo"),
  ILearnerHomeService: Symbol.for("ILearnerHomeServices"),
  ILearnerProfileService: Symbol.for("ILearnerProfileService"),
  IProfesionalVerificationService: Symbol.for("IProfesionalVerificationService"),
  ILearnerHomeController: Symbol.for("ILearnerHomeController"),
  ILearnerProfileController: Symbol.for("ILearnerProfileController"),
  IProfesionalVerificationController: Symbol.for("IProfesionalVerificationController"),
  IRefreshController: Symbol.for("IRefreshController"),
  IEmailAuthService: Symbol.for("IEmailAuthService"),
  IAuthOrchestrator: Symbol.for(" IAuthOrchestrator"),
  ITokenService: Symbol.for("ITokenService"), //common-services
  IPasswordResetService: Symbol.for("IPasswordResetService"),
  IRoleRepoFactory: Symbol.for("IRoleRepoFactory"),
  IEmailService: Symbol.for("EmailService"),
  IOtpService: Symbol.for("OtpService"),
  IPasswordService: Symbol.for("PasswordService"),
  IRefreshService: Symbol.for("RefreshService"),
  ICloudinaryService: Symbol.for("CloudinaryService"),
  IUserDtoMapper: Symbol.for("IUserDtoMapper"),
  IProviderAuth: Symbol.for("IProviderAuth"),
  IAuthController: Symbol.for("IAuthController"),
  IS3Service: Symbol.for("IS3Service"),
  ILearnerProfileDto: Symbol.for("ILearnerProfileDto"),
  IAuthenticateMiddleware: Symbol.for("IAuthenticateMiddleware"),
  IProfessionalProfileRepo: Symbol.for("IProfessionalProfileRepo"),
  IProfessionalProfileService: Symbol.for("IProfessionalProfileService"),
  IProfessionalProfileController: Symbol.for("IProfessionalProfileController"),
  IProfessionalDashboardDtoMap: Symbol.for("IProfessionalDashboardDtoMap"),
  IProfessionalDashboardService: Symbol.for("IProfessionalDashboardService"),
  IProfessionalDashboardController: Symbol.for("IProfessionalDashboardController"),
  IAdminDashboardService: Symbol.for("IAdminDashboardService"),
  IAdminDashboardController: Symbol.for("IAdminDashboardController"),
  IAdminUserManagementService: Symbol.for("IAdminUserManagementService"),
  IAdminUserManagementController: Symbol.for("IAdminUserManagementController"),
  ICourseModel: Symbol.for("ICourseModel"),
  ICourseRepo: Symbol.for("ICourseRepo"),
  ILessonModel: Symbol.for("ILessonModel"),
  ILessonRepo: Symbol.for("ILessonRepo"),
  IAdminModel: Symbol.for("IAdminModel"),
  ICategoryModel: Symbol.for("ICategoryModel"),
  ISubCategoryModel: Symbol.for("ISubCategory"),
  ICategoryRepo: Symbol.for("ICategoryRepo"),
  ISubCategoryRepo: Symbol.for("ISubCategory"),
  ICategoryService: Symbol.for("ICategoryService"),
  ICategoryController: Symbol.for("ICategoryController"),
  ISubCategoryService: Symbol.for("ISubCategoryService"),
  ISubCategoryController: Symbol.for("ISubCategoryController"),
  ICourseService: Symbol.for("ICourseService"),
  ICourseController: Symbol.for("ICourseController"),
  VideoCompressService: Symbol.for("VideoCompressService"),
  ImageCompressService: Symbol.for("ImageCompressService"),
  IChapterModel: Symbol.for("IChapterModel"),
  IChapterRepo: Symbol.for("IChapterRepo"),
  IChapterService: Symbol.for("IChapterService"),
  IChapterController: Symbol.for("IChapterController"),
};
