export const TYPES = {
  ILearnerProfileModel: Symbol.for("ILearnerProfileModel"),
  IUserModel: Symbol.for("IUserModel"), //models
  IProfessionalProfileModel: Symbol.for("ProfesionalProfileModel"),
  IAdminProfileModel: Symbol.for("IAdminProfileModel"),
  ILearnerProfileRepo: Symbol.for("ILearnerProfileRepo"), //Repos
  IProfesionalProfileRepo: Symbol.for("IProfesionalProfileRepo"),
  IRedisRepository: Symbol.for("IRedisRepository"),
  IAdminProfile: Symbol.for("IAdminProfileRepository"),
  IUserRepo: Symbol.for("IUserRepo"),
  ILearnerHomeService: Symbol.for("ILearnerHomeServices"),
  ILearnerProfileService: Symbol.for("ILearnerProfileService"),
  IProfesionalVerificationService: Symbol.for("IProfesionalVerificationService"),
  ILearnerHomeController: Symbol.for("ILearnerHomeController"),
  ILearnerProfileController: Symbol.for("ILearnerProfileController"),
  IProfesionalVerificationController: Symbol.for("IProfesionalVerificationController"),
  IRefreshController: Symbol.for("IRefreshController"),
  IEmailAuthService: Symbol.for("IEmailAuthService"),
  IAuthOrchestrator: Symbol.for(" IAuthOrchestrator"),
  ITokenService: Symbol.for("ITokenService"), //common-services
  IPasswordResetService: Symbol.for("IPasswordResetService"),
  IRoleRepoFactory: Symbol.for("IRoleRepoFactory"),
  IEmailService: Symbol.for("EmailService"),
  IOtpService: Symbol.for("OtpService"),
  IPasswordService: Symbol.for("PasswordService"),
  IRefreshService: Symbol.for("RefreshService"),
  ICloudinaryService: Symbol.for("CloudinaryService"),
  IUserDtoMapper: Symbol.for("IUserDtoMapper"),
  IProviderAuth: Symbol.for("IProviderAuth"),
  IAuthController: Symbol.for("IAuthController"),
  IS3Service: Symbol.for("IS3Service"),
  ILearnerProfileDto: Symbol.for("ILearnerProfileDto"),
  IAuthenticateMiddleware: Symbol.for("IAuthenticateMiddleware"),
};
