export const CHAT_KEY = {
  SESSION_BOOK: "SESSION_BOOK",
  RESET_PASSWORD: "RESET_PASSWORD",
  CONTACT_SUPPORT: "CONTACT_SUPPORT",
  PRICING_INFO: "PRICING_INFO",
  COURSE_RECOMMENDATION: "COURSE_RECOMMENDATION",
} as const;

export type ChatKey = (typeof CHAT_KEY)[keyof typeof CHAT_KEY];
